### ISSUE TITLE
AT-X互換性

### ISSUE THREAD

**Issue by lovesyk** [monyone/node-arib-subtitle-timedmetadater#1]
環境
node-arib-subtitle-timedmetadater 4.0.9
EPGStation 2.6.20
FFmpeg 4.1.6/4.2.4/5.0.1

Issue
完全な初心者で申し訳ありませんが、EPGStationで初録画して、HLSストリーミングしようとしています。
FFmpegは数秒後、どんなバージョンでも以下のエラーで落ちます：
> [DEBUG] stream - [hls @ 0x56363f705dc0] Application provided invalid, non monotonically increasing dts to muxer in stream 4: 4178091 >= 4123255
> av_interleaved_write_frame(): Invalid argument

このパッケージは字幕の表示のために使われいていると気づいて、4.0.8に戻したら無事に字幕付きの再生ができました。
4.0.9でも以下のpushを削除すれば問題なく再生できます。
https://github.com/monyone/node-arib-subtitle-timedmetadater/commit/73638517b6ab427829e1f8ab45059e2df47bd4b4#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R382

コードの内容は詳しくないが、録画はAT-XでVFRの部分もあるらしいです。それは原因かどうかわかりませんけど…

**Comment by monyone** [comment]
@lovesyk 
ご利用ありがとうございます、ご不便おかけしています事、お詫び申し上げます。

エラーの内容についてなのですが、
文字スーパーに PCR の値を利用している際に、PTS を利用する字幕との間で
時間的に連続せず、PTS による字幕の前になる ID3 データが発生すると、
この DTS エラー、というものが起こる、ということのようです。
(なので、DTS が単調に増えていない (減っていて過去だぞ) と言われています)

ですので、文字スーパーを Push しなければ発生しないため、
ご指摘の部分を消去すると発生せず、問題がなくなります。

EPGStation でこのバージョンがはいっていて、
文字スーパーが入るような使い方がされていると、認識しておりませんでした。
誤った認識のまま放置しており、申し訳ありませんでした。

このバージョンは Revert しておきますが、npm だと取り下げが出来ず
EPGStation の更新も止まっているため、バージョンを上げる事しかできません。
手作業でアップデートをするように、何卒お願い申し上げます。

**Comment by monyone** [comment]
@lovesyk こちら 4.0.10 で 4.0.8 の内容に戻しました
最新版のこちらを使っていただければ幸いです

**Comment by lovesyk** [comment]
説明と早期な対応ありがとうございます！

EPGStationはどうやらボットでdependencyのバージョン管理しているみたいなので、いつか新しいバージョンが出たらarib-subtitle-timedmetadaterも更新されますでしょうね。
